### ISSUE TITLE
"No reviews yet - be the first" inaccurate

### ISSUE THREAD

**Issue by alyshkalia** [iftechfoundation/ifdb-suggestion-tracker#458] opened 2024-04-05 23:49 UTC
This text appears on game pages when there are no ratings rather than when there are no reviews, so it still shows up when there are reviews but no ratings.

**Comment by dfabulich** [comment] 2024-08-12 04:38
This is a duplicate of #377

**Closed by dfabulich** 2024-08-12 04:38 UTC
